name: Code Quality

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.1', '8.2', '8.3']

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: cs2pr

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Run phpcs
      run: composer run-script ci-phpcs -- --report=checkstyle | cs2pr --graceful-warnings

    - name: Run phpstan
      run: composer run-script ci-phpstan
